Add /checkfree and /labfree (and other neat things)
DistroByte/calendarbot pull request #1
Opened 2023-01-17 17:55 UTC by NightmarishBlue

Added some functions, fixed some old things, and refactored (sorry)

2023-01-17 20:57 UTC, DistroByte requested changes
Breaking from existing codebase style

I'm not sure we need to store all the IDs of the rooms, these are as likely to change as the actual timetable data.

Does the Discord version need to be updated? If not, why change it. Discord v13 is using the correct gateway, and if discord change that it'll be after I leave. Shouldn't be needed.

The register and delete bot command files should be automatic and shouldn't require input from the user.

I would advise renaming the command to `checkroom` and if possible return a timetable to show available hours in that room.

Comments go a long way also to improving readability - guilty on that front but I had no intention of anyone reading or modifying this code,

2023-01-25 21:39 UTC, NightmarishBlue commented
Code has been commented and formatted nicely, I hope. 

Changed the command as specified to `checkrooms` and added support for custom time ranges in the underlying function. 

The registration scripts have been altered to need no input beyond execution.

As for obtaining room IDs, the room codes can't be easily queried in batches, or if they are I haven't found a way to make the opentimetable API do it. Either the site's keyword search can be performed for each one, or the API can be queried for campus location info, which has to be repeated for some 15 pages and scraped.

The smart thing would be to periodically periodically update the cache of room codes and their identities. I personally highly doubt existing timetable data will change for the rooms, but if you care enough I can add a scheduled task to generate the dictionary every once in a while.

Also, I fixed the channel sending feature, and added support for finding tomorrow's timetable info instead, although I don't know if you or anyone else would actually prefer that.

2023-01-25 22:01 UTC, DistroByte approved these changes

2023-01-25 22:01 UTC, merged

2023-01-25 22:02 UTC, DistroByte commented
Cheers for the work, I'll update the bot later this evening for you!